#!/bin/sh
# Environment settings for running programs with the SIL version of mono
# Set MONO_ENVIRON to this file's pathname, then run, for example,
#    /opt/mono-sil/bin/mono --debug LfMerge.exe
# These settings assume that the packaged SIL Mono is installed in /opt/mono-sil.
# Note that this file is intended to be "sourced", not "executed".

# the sourcing script should cd/pushd to the directory containing this script
BASE="$(pwd)"
[ -z "$BUILD" ] && BUILD=Debug
[ -z "$MONO_PREFIX" ] && MONO_PREFIX=/opt/mono-sil


MONO_RUNTIME=v4.0.30319
MONO_DEBUG=explicit-null-checks
MONO_ENV_OPTIONS="-O=-gshared"

COMPONENTS_MAP_PATH=/usr/lib/fieldworks
ICU_DATA=/usr/share/fieldworks/Icu54

################################################################################################

if [ "$RUNMODE" = "INSTALLED" ]
then
	# Add the installation directory to the library paths
	LD_LIBRARY_PATH="${BASE}:${LD_LIBRARY_PATH}"
	MONO_PATH="${BASE}:${MONO_PATH}"
else
	# Add the build output to paths
	PATH="${BASE}/output/${BUILD}:${PATH}"
	LD_LIBRARY_PATH="${BASE}/output/${BUILD}:${LD_LIBRARY_PATH}"
	MONO_PATH="${BASE}/output/${BUILD}:${MONO_PATH}"
fi

################################################################################################

if [ "$RUNMODE" = "PACKAGE" -o "$RUNMODE" = "INSTALLED" ]
then
	# Add packaged mono items to paths
	PATH="/opt/mono-sil/bin:${PATH}"
	LD_LIBRARY_PATH="/opt/mono-sil/lib:${LD_LIBRARY_PATH}"
	PKG_CONFIG_PATH="/opt/mono-sil/lib/pkgconfig:${PKG_CONFIG_PATH}"
	MONO_GAC_PREFIX="/opt/mono-sil:/usr"
else
	# Add locally-built mono items to paths
	# We also add the default values for PKG_CONFIG_PATH - MonoDevelop resets the PKG_CONFIG_PATH
	# environment variable if we're running under a different Mono runtime so that some
	# packages that got installed in standard locations can't be found otherwise.
	PATH="${MONO_PREFIX}/bin:${PATH}"
	LD_LIBRARY_PATH="${MONO_PREFIX}/lib:${LD_LIBRARY_PATH}"
	PKG_CONFIG_PATH="${MONO_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig:/lib/pkgconfig:/usr/lib/pkgconfig"
	MONO_GAC_PREFIX="${MONO_PREFIX}:/usr"
fi

################################################################################################

if [ "$RUNMODE" != "PACKAGEBUILD" ]
then
	# add path to FDO assemblies
	MONO_PATH="$(pkg-config --variable=assemblies_dir libfieldworks-fdo):$MONO_PATH"
fi

LD_LIBRARY_PATH="/usr/lib/fieldworks:${LD_LIBRARY_PATH}"
FW_ROOTCODE=/usr/share/fieldworks

MONO_TRACE_LISTENER="Console.Out"

# if debugging for performance unset DEBUG_ENABLE_PTR_VALIDATION env var.
#export DEBUG_ENABLE_PTR_VALIDATION=1

export \
	PATH LD_LIBRARY_PATH PKG_CONFIG_PATH LD_PRELOAD \
	COMPONENTS_MAP_PATH ICU_DATA \
	MONO_PATH \
	MONO_RUNTIME MONO_PREFIX MONO_GAC_PREFIX \
	MONO_TRACE_LISTENER \
	MONO_DEBUG MONO_ENV_OPTIONS \
	FW_ROOTCODE

# set HGRCPATH so that we ignore ~/.hgrc files which might have content that is
# incompatible with our version of Mercurial
export HGRCPATH=
