#!/bin/bash

# Highest FW database model version that lfmerge supports in the current git branch
MaxDbVersion=7000072

# Minimal FW database model version that lfmerge supports in the current git branch
MinDbVersion=7000072

# FW database model version to package
CurDbVersion="$1"

if [ "$CurDbVersion" == "" ]; then
	CurDbVersion=$MaxDbVersion
fi

PackageVersion=${PackageVersion:-0.0.1}

cd "$(dirname $0)"

AllLfMergeVersions=$(for ((i=$MinDbVersion; i<=$MaxDbVersion; i++)); do \
		echo -n "lfmerge-$i (>= ${PackageVersion}),"; \
	done)

cpp -D__DatabaseVersion__="$CurDbVersion" -D__MaxDbVersion__="$MaxDbVersion" \
	-D__allLfMergeVersions__="$AllLfMergeVersions" -P -traditional-cpp control.in -o control

sed "s/__DatabaseVersion__/$CurDbVersion/g" changelog.in > changelog
sed "s/__DatabaseVersion__/$CurDbVersion/g" rules.in > rules && chmod +x rules
