#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f $0))

# Are we running on a dev machine?
if [[ $(basename $SCRIPT_DIR) == 70* ]]; then
	RUNMODE=INSTALLED
else
	RUNMODE=DEVELOP
fi

[ -z ${DBVERSION} ] && DBVERSION=$(basename $SCRIPT_DIR)

if [[ $DBVERSION != 70* ]]; then
	DBVERSION=$(basename $(find /usr/lib/lfmerge -maxdepth 1 -type d -name [0-9]\* | sort | tail -n 1))
fi


if [ "$RUNMODE" = "INSTALLED" ]; then
	LIB=/usr/lib/lfmerge/$DBVERSION
	SHARE=/usr/share/lfmerge/$DBVERSION
	DBVERSIONPATH=$LIB
else
	LIB=$SCRIPT_DIR
	SHARE=$SCRIPT_DIR
	DBVERSIONPATH=/usr/lib/lfmerge/$DBVERSION
fi

cd "$SHARE"
. ./environ
cd "$LIB"

exec dotnet run "$LIB"/ChorusMerge.exe "$@"
