name: build-base-image

on:
  # Only run this workflow manually, to ensure it WON'T run with every commit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up buildx for Docker
      uses: docker/setup-buildx-action@v2.4.1

    - name: Login to GHCR
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build base Docker image (builder)
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ghcr.io/sillsdev/lfmerge-base:sdk
        context: docker
        file: Dockerfile.builder-base

    - name: Build base Docker image (runtime)
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ghcr.io/sillsdev/lfmerge-base:runtime
        context: docker
        file: Dockerfile.runtime-base

    - name: List Docker images to verify build
      run: docker image ls
