name: docker-build

on:
  push:
    branches: [ master, qa, live, fieldworks8-master, fieldworks8-qa, fieldworks8-live ]
  pull_request:
    branches: [ master, fieldworks8-master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # As of 2021-11-24, we build LfMerge for LCM DB versions 68-72 (and there is no 71)
    strategy:
      matrix:
        dbversion: [7000068, 7000069, 7000070, 7000072]
        distro: [ 'bionic' ]

    steps:
      - name: Dump GitHub context for testing
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Echo dbversion and current ref
        env:
          DBVERSION: ${{ matrix.dbversion }}
          REFNAME: ${{ github.ref_name }}
          BASEREF: ${{ github.base_ref }}
        run: echo "DB version ${DBVERSION} and ref ${GITHUB_REF} (ref name ${REFNAME} and base ref ${BASEREF}) with current SHA ${GITHUB_SHA}"

      - name: Decide if this build configuration should run
        id: should_run
        run: true
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.base_ref, 'fieldworks8-') && matrix.dbversion < 7000072) || (github.event_name == 'pull_request' && !startsWith(github.base_ref, 'fieldworks8-') && matrix.dbversion >= 7000072) }}

      - name: Check out current branch
        uses: actions/checkout@v2
        if: steps.should_run.outcome == 'success'
        with:
          fetch-depth: 0  # All history for all tags and branches, since GitVersion needs that

      - name: Check out FW8 branch
        uses: actions/checkout@v2
        if: github.event_name == 'push' && !startsWith(github.ref_name, 'fieldworks8-') && matrix.dbversion < 7000072 && steps.should_run.outcome == 'success'
        with:
          ref: fieldworks8-${{ github.ref_name }}
          fetch-depth: 0  # All history for all tags and branches, since GitVersion needs that

      - name: Verify current branch
        run: git branch --contains HEAD --format '%(refname)'
        if: steps.should_run.outcome == 'success'

      - name: Calculate version number
        id: version
        if: steps.should_run.outcome == 'success'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo Start
          REV=${GITHUB_REF:-$(git rev-parse --symbolic-full-name HEAD)}
          DESCRIBE=$(git describe --long --match "v*")
          MAJOR=$(echo "$DESCRIBE" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/\1/')
          MINOR=$(echo "$DESCRIBE" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/\2/')
          PATCH=$(echo "$DESCRIBE" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/\3/')
          # TODO: Detect need for minor/major updates and increment those instead of PATCH
          PATCH=$((${PATCH} + 1))
          COMMIT_COUNT=$(echo "$DESCRIBE" | sed -E 's/^[^-]+-([^-]+)-.*$/\1/')
          COMMIT_HASH=$(echo "$DESCRIBE" | sed -E 's/^[^-]+-[^-]+-g(.*)$/\1/')
          MajorMinorPatch="${MAJOR}.${MINOR}.${PATCH}"
          AssemblySemVer="${MajorMinorPatch}.${BUILD_NUMBER}"
          AssemblySemFileVer="${MajorMinorPatch}.0"
          InformationalVersion="${DESCRIBE}"
          echo "Calculating name from ${REV}"
          if [ -z ${REV} ]; then
            echo Failed to get a meaningful commit name
          fi
          echo Got commit name ${REV}
          RESULT=notfound
          if echo "${REV}" | grep -E '^refs/pull/'; then
            echo Found PR
            RESULT=$(echo "${REV}" | sed -E 's/^refs\/pull\/([0-9]+)\/merge/\1/')
          fi
          if echo "${REV}" | grep -E '^refs/heads/'; then
            echo Found branch
            RESULT=$(echo "${REV}" | sed -E 's/^refs\/heads\///')
          fi
          if echo "${REV}" | grep -E '^refs/tags/'; then
            echo Found tag
            RESULT=$(echo "${REV}" | sed -E 's/^refs\/tags\///')
          fi
          echo Will calculate version from "${RESULT}" and "${MAJOR}.${MINOR}.${PATCH} with $COMMIT_COUNT commits since then, and current hash $COMMIT_HASH"

          case "$REV" in
            refs/heads/master | refs/heads/fieldworks8-master)
              PRERELEASE="~alpha.${BUILD_NUMBER}"
              ;;

            refs/heads/qa | refs/heads/fieldworks8-qa)
              PRERELEASE="~beta.${BUILD_NUMBER}"
              ;;

            refs/heads/live | refs/heads/fieldworks8-live)
              PRERELEASE=
              ;;

            refs/pull/*)
              PR_NUMBER=$(echo "${REV}" | sed -E 's/^refs\/pull\/([0-9]+)\/merge/\1/')
              PRERELEASE="~PR${PR_NUMBER}.${BUILD_NUMBER}"
              ;;

            refs/heads/*)
              PRERELEASE="~${REV##refs/heads/}.${BUILD_NUMBER}"
              ;;

            *)
              echo "Could not determine version number from ${REV}"
              echo "::error ::Could not determine version number from ${REV}"
              exit 1

          esac
          DebPackageVersion=${MAJOR}.${MINOR}.${PATCH}${PRERELEASE}
          echo "Will build package version ${DebPackageVersion}"
          echo "::set-output name=DebPackageVersion::${DebPackageVersion}"
          echo "::set-output name=MajorMinorPatch::${MajorMinorPatch}"
          echo "::set-output name=AssemblySemVer::${AssemblySemVer}"
          echo "::set-output name=AssemblySemFileVer::${AssemblySemFileVer}"
          echo "::set-output name=InformationalVersion::${InformationalVersion}"

      # TODO: Step that calculates version number from `git-describe` and prerelease name based on branch
      # That will allow us to ditch GitVersion, which is randomly failing on some PR builds with no rhyme or reason

      - name: Check out files needed for Docker build if on older branches
        # TODO: Will not be needed once Docker build is merged into fieldworks8-master
        if: matrix.dbversion < 7000072 && steps.should_run.outcome == 'success'
        run:
          git checkout refs/remotes/origin/master -- docker Dockerfile

      - name: Build base Docker image
        if: steps.should_run.outcome == 'success'
        run: docker build -t lfmerge-builder-base --target lfmerge-builder-base .

      - name: Build DBVersion-specific Docker image
        if: steps.should_run.outcome == 'success'
        run: docker build --build-arg DbVersion=${{matrix.dbversion}} -t lfmerge-build-${{matrix.dbversion}} .

      - name: Run the build container
        if: steps.should_run.outcome == 'success'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          DebPackageVersion: ${{ steps.version.outputs.DebPackageVersion }}
          MajorMinorPatch: ${{ steps.version.outputs.MajorMinorPatch }}
          AssemblySemVer: ${{ steps.version.outputs.AssemblySemVer }}
          AssemblySemFileVer: ${{ steps.version.outputs.AssemblySemFileVer }}
          InformationalVersion: ${{ steps.version.outputs.InformationalVersion }}
        run: docker run --env "BUILD_NUMBER=${BUILD_NUMBER}" --env "DebPackageVersion=${DebPackageVersion}" --env "MajorMinorPatch=${MajorMinorPatch}" --env "AssemblySemVer=${AssemblySemVer}" --env "AssemblySemFileVer=${AssemblySemFileVer}" --env "InformationalVersion=${InformationalVersion}" --name tmp-lfmerge-build-${{matrix.dbversion}} lfmerge-build-${{matrix.dbversion}}

      - name: Collect Debian images
        if: steps.should_run.outcome == 'success'
        run: docker container cp tmp-lfmerge-build-${{matrix.dbversion}}:/home/builder/packages/lfmerge/finalresults ./

      - uses: actions/upload-artifact@v2
        if: steps.should_run.outcome == 'success'
        with:
          name: lfmerge-deb-files
          path: finalresults/lfmerge*deb

      # TODO: If `live` branch, then create release
