name: release

on:
  workflow_call:
    inputs:
      MsBuildVersion:
        required: true
        type: string
      TagFor7000072:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Ensure all TagForDbVersion outputs were present
      env:
        TAG72: ${{ inputs.TagFor7000072 }}
      run: |
        echo "Tag for FW9 (DbVersion 72): (${TAG72})"

    - name: Tag release branches
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        TAG72: ${{ inputs.TagFor7000072 }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git tag -f -a -m "Release ${TAG72}" "${TAG72}" "refs/remotes/origin/master"
        git push -v origin "${TAG72}"

    - name: Calculate Docker tags
      id: docker_tag
      if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
      env:
        MS_BUILD_VERSION: ${{ inputs.MsBuildVersion }}
      run: |
        if [ "${GITHUB_REF}" = 'refs/heads/master' ]
        then
          TAGS=ghcr.io/sillsdev/lfmerge:${MS_BUILD_VERSION},ghcr.io/sillsdev/lfmerge:latest
        else
          TAGS=ghcr.io/sillsdev/lfmerge:${MS_BUILD_VERSION}
        fi
        echo "DockerTags=${TAGS}" >> $GITHUB_OUTPUT

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        # No name specified, so will download all artifacts
        path: all-tarballs

    - name: Verify that download step worked
      run: ls -lR all-tarballs

    - name: Uncompress build artifacts
      run: for f in all-tarballs/*/*.tar.gz; do gzip -cd "${f}" | tar xf -; done

    - name: Verify that uncompress step worked
      run: ls -lR tarball

    - name: Login to GHCR
      if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build final Docker image
      id: lfmerge_image
      uses: docker/build-push-action@v4.0.0
      with:
        push: ${{(github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'))}}
        tags: ${{ steps.docker_tag.outputs.DockerTags }}
        context: .
        file: Dockerfile.finalresult

    - name: Show metadata from LfMerge image build step
      run: echo "$METADATA"
      env:
        METADATA: ${{ steps.lfmerge_image.outputs.metadata }}

    - name: List Docker images to verify build
      run: docker image ls

